apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assignment-arber-ingress
  namespace: {{.Values.namespace}}
  annotations: 
    alb.ingress.kubernetes.io/group.name: "common-alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
spec:
  ingressClassName: alb
  rules:
    - host: {{.Values.hostname}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arber-service
                port:
                  number: 80